<?php
//$startTime = microtime(true);
try {
//    $model = Mage::getModel('betaout_amplify/key');
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {

        $c = Mage::getSingleton('customer/session')->getCustomer();
        $customer = Mage::getModel('customer/customer')->load($c->getId());

        $identity = $customer->getEmail();
    }
    else {
        $identity= Mage::getModel('core/cookie')->get('amplify_email');
      }
   
        ?>
        <script type="text/javascript">
            var Amplify = "";
            _bOutCW = <?php echo Mage::getStoreConfig("betaout_amplify_options/settings/AmplifyConnect_Widget"); ?>;
            _bOutST = "<?php echo Mage::getStoreConfig("betaout_amplify_options/settings/shareTracking"); ?>";
            urlTracking = "<?php echo Mage::getStoreConfig("betaout_amplify_options/settings/urlTracking"); ?>";
            _bOutAKEY = '<?php echo Mage::getStoreConfig("betaout_amplify_options/settings/amplify_key"); ?>';
            _bOutPID = '<?php echo Mage::getStoreConfig("betaout_amplify_options/settings/amplify_projectId"); ?>';
            
                var _bOut = _bOut || [];
                function _bOutS(u) {
                var d = document, f = d.getElementsByTagName("script")[0], _sc = d.createElement("script");
                _sc.type = "text/javascript";
                _sc.async = true;
                _sc.src = u;
                f.parentNode.insertBefore(_sc, f);
                }
                _bOutS("//d22vyp49cxb9py.cloudfront.net/jal.min.js");

                _bOut.push(["identify", {
                        "email": "<?php echo $identity; ?>",
                        "name": ""
                 }]);

        </script>

        <?php
 
} catch (Exception $ex) {
    
}
//$endTime = microtime(true);
//echo "total Execution time ==" . ($endTime - $startTime);
?>
