<?php
//$startTime = microtime(true);
try {
//    $model = Mage::getModel('betaout_amplify/key');
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {

        $c = Mage::getSingleton('customer/session')->getCustomer();
        $customer = Mage::getModel('customer/customer')->load($c->getId());

        $identity = $customer->getEmail();
    }
    else {
        $identity= Mage::getModel('core/cookie')->get('amplify_email');
    }
    if (Mage::getStoreConfig('betaout_amplify_options/settings/amplify_verified')) {
        ?>
       
        <?php
    };
} catch (Exception $ex) {
    
}
//$endTime = microtime(true);
//echo "total Execution time ==" . ($endTime - $startTime);
?>
