<?php
//$startTime = microtime(true);
try {
   $identity="";
   $customer_id="";
    if (Mage::getSingleton('customer/session')->isLoggedIn()) {

        $c = Mage::getSingleton('customer/session')->getCustomer();
        $customer = Mage::getModel('customer/customer')->load($c->getId());
        $identity = $customer->getEmail();
        $customer_id = $customer->getId();
    }
    else {
        $identity= Mage::getModel('core/cookie')->get('amplify_email');
      }
   
        ?>
        <script type="text/javascript">
            var _bout = _bout || [];
            var _boutAKEY = '<?php echo Mage::getStoreConfig("betaout_amplify_options/settings/amplify_key"); ?>';
            var _boutPID = '<?php echo Mage::getStoreConfig("betaout_amplify_options/settings/amplify_projectId"); ?>';
               
           
            var d = document, f = d.getElementsByTagName("script")[0], _sc = d.createElement("script");
            _sc.type = "text/javascript";
            _sc.async = true;
            _sc.src = "//d22vyp49cxb9py.cloudfront.net/jal-v2.min.js";
            f.parentNode.insertBefore(_sc, f);
            _bout.push(["identify", {
                    "customer_id": "<?php echo $customer_id;?>",
                    "email": "<?php echo $identity; ?>",
                    "phone": "",
                    "gcm_id": "",
                    "apn_id": ""
                }
            ]);
         </script>

        <?php
 
} catch (Exception $ex) {
    
}
//$endTime = microtime(true);
//echo "total Execution time ==" . ($endTime - $startTime);
?>
