<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//if (Mage::getSingleton('customer/session')->isLoggedIn()) {
//
///* Get the customer data */
//$customer = Mage::getSingleton('customer/session')->getCustomer();
///* Get the customer's email address */
//$customer_email = $customer->getEmail();
//
//}
//
//
//
//$collection = Mage::getModel('sales/order')
//                    ->getCollection()
//                      ->addAttributeToFilter('customer_email',array('like'=>$customer_email));
//
//foreach($collection as $order){
//    //do something
//    $order_id = $order->getId();
//
//
//
//$order = Mage::getModel("sales/order")->load($order_id); //load order by order id 
//
//$ordered_items = $order->getAllItems(); 
//
//foreach($ordered_items as $item){     //item detail     
//
//echo $item->getItemId(); //product id     
//
//echo $item->getSku();    
// echo $item->getQtyOrdered(); //ordered qty of item    
//
// echo $item->getName();   
//
// } 
//}
?>