<!--<script>
   function addEvent() {
        if ((typeof (Amplify) != 'undifined' && typeof (Amplify) == "object")) {
            Amplify.addEvent("", {'viewed_wishlist': {
                    'viewed_wishlist': 1
                }});
        }
        else {
            setTimeout(addEvent, 10);
        }
    }
    addEvent();
</script>-->
<?php
//try{
//require_once MAGENTO_ROOT . '/app/code/community/Betaout/Amplify/Model/Amplify.php';
// $key = Mage::getStoreConfig('betaout_amplify_options/settings/amplify_key');
//    $secret = Mage::getStoreConfig('betaout_amplify_options/settings/amplify_secret');
//
//    $projectId = Mage::getStoreConfig('betaout_amplify_options/settings/amplify_projectId');
//    $amplify = new Amplify($key, $secret, $projectId);
//     $model = Mage::getModel('betaout_amplify/key');
//$identity = $model->getCustomerIdentity();
//$amplify->event($identity,array('viewed_wishlist'=>false));
//} catch (Exception $ex) {
//
//}
//
?>
<?php




